[package]
name = "pointspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
position_velocity_macros = { path = "../position_velocity_macros" }
